import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const site=JSON.parse(readFileSync('content/seo.json','utf8'));
const {title,liveUrl:base,repository,subject,description,color,paper,headline,summary,article,sections,label}=site;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=s=>JSON.stringify(s).replace(/</g,'\\u003c');
const articlePath=`guides/${article}.html`;
const articles=[{slug:article,title:headline,description:summary,published:'2026-09-08',sections:sections.map(([heading,text])=>({heading,paragraphs:[text]})),questions:[],references:site.reference?[{label:site.reference[0],url:site.reference[1]}]:[]},...(site.articles||[])];
const articlePaths=articles.map(a=>`guides/${a.slug}.html`);
if(new Set(articlePaths).size!==articlePaths.length)throw new Error('Duplicate guide URL');
const sectionId=(index)=>'section-'+(index+1);
const displayDate=value=>new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z'));

const website={'@type':'WebSite','@id':base+'#website',url:base,name:title,description,inLanguage:'en'};
function head(name,desc,path='',type='WebPage',extra={}){
 const url=base+path;
 const verification=path==='' && site.googleVerification ? `<meta name="google-site-verification" content="${esc(site.googleVerification)}">` : '';
 const page={'@type':type,'@id':url+'#page',url,name,description:desc,isPartOf:{'@id':base+'#website'},inLanguage:'en',...extra};
 const graph=[website,page];
 if(path){
  const crumbs=[{'@type':'ListItem',position:1,name:title,item:base}];
  if(path.startsWith('guides/')&&path!=='guides/')crumbs.push({'@type':'ListItem',position:2,name:'Guides',item:base+'guides/'});
  crumbs.push({'@type':'ListItem',position:crumbs.length+1,name:extra.headline||name,item:url});
  graph.push({'@type':'BreadcrumbList',itemListElement:crumbs});
 }
 return `<meta charset="UTF-8">${verification}<meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(name)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${esc(url)}"><meta name="theme-color" content="${color}"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><meta property="og:type" content="${type==='Article'?'article':'website'}"><meta property="og:site_name" content="${esc(title)}"><meta property="og:title" content="${esc(name)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${esc(url)}"><meta property="og:locale" content="en_US"><meta property="og:image" content="${base}social-card.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${esc(title+' — '+subject)}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(name)}"><meta name="twitter:description" content="${esc(desc)}"><meta name="twitter:image" content="${base}social-card.png"><meta name="twitter:image:alt" content="${esc(title+' — '+subject)}"><script type="application/ld+json">${json({'@context':'https://schema.org','@graph':graph})}</script>`;
}
function write(path,body){mkdirSync('public/'+path.split('/').slice(0,-1).join('/'),{recursive:true});writeFileSync('public/'+path,body.trimEnd()+'\n');}
const nav=`<header class="guide-nav"><a href="/" class="guide-brand">${esc(title)}</a><nav aria-label="Main navigation"><a href="/guides/">Guides & search</a><a href="/about.html">About</a><a href="/#/import">Open the app</a></nav></header>`;
const footer=`<footer class="guide-footer"><a href="/">${esc(title)}</a><a href="/guides/">Search guides</a><a href="/about.html">About this site</a><a href="/privacy.html">Privacy</a><a href="${repository}">Source code on GitHub</a></footer>`;
function page(name,desc,path,body,type='WebPage',extra={}){return `<!doctype html><html lang="en"><head>${head(name,desc,path,type,extra)}<link rel="stylesheet" href="/editorial.css"></head><body class="guide-page"><a class="guide-skip" href="#content">Skip to content</a>${nav}<main id="content">${body}</main>${footer}</body></html>`;}
const status='Live record connections are awaiting production activation. Public guides are available now; deployment alone does not establish a completed patient connection.';
const relation=`${title} focuses on ${subject.toLowerCase()}. Its own interface, public documentation and source repository support the product’s continued development.`;
for(const a of articles){
 const path=`guides/${a.slug}.html`;
 const sources=(a.references||[]).map(r=>`<li><a href="${esc(r.url)}">${esc(r.label)}</a></li>`).join('');
 const sourcesBlock=sources?`<section aria-labelledby="references-heading"><h2 id="references-heading">Sources and implementation</h2><ul>${sources}</ul></section>`:'';
 const toc=`<nav class="guide-toc" aria-label="On this page"><p>On this page</p><ol>${a.sections.map((s,i)=>`<li><a href="#${sectionId(i)}">${esc(s.heading)}</a></li>`).join('')}${a.finchnode?`<li><a href="#connection-context">${esc(a.finchnode.heading)}</a></li>`:''}${a.questions?.length?'<li><a href="#questions">Questions about this guide</a></li>':''}</ol></nav>`;
 const content=a.sections.map((s,i)=>`<section aria-labelledby="${sectionId(i)}"><h2 id="${sectionId(i)}">${esc(s.heading)}</h2>${s.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}${s.items?`<ol>${s.items.map(p=>`<li>${esc(p)}</li>`).join('')}</ol>`:''}${s.code?`<pre class="guide-code" tabindex="0" aria-label="${esc(s.heading)} code example"><code>${esc(s.code)}</code></pre>`:''}${s.links?.length?`<p class="guide-sources">Sources: ${s.links.map(r=>`<a href="${esc(r.url)}">${esc(r.label)}</a>`).join(' · ')}</p>`:''}</section>`).join('');
 const connection=a.finchnode?`<section aria-labelledby="connection-context"><h2 id="connection-context">${esc(a.finchnode.heading)}</h2><p>${esc(a.finchnode.text)}</p><p><a href="${esc(a.finchnode.url)}">${esc(a.finchnode.label)}</a></p></section>`:'';
 const questions=a.questions?.length?`<section aria-labelledby="questions"><h2 id="questions">Questions about this guide</h2>${a.questions.map(q=>`<h3>${esc(q.question)}</h3><p>${esc(q.answer)}</p>`).join('')}</section>`:'';
 const related=`<aside class="related-guides" aria-labelledby="related-heading"><h2 id="related-heading">More from ${esc(title)}</h2><ul>${articles.filter(other=>other.slug!==a.slug).map(other=>`<li><a href="/guides/${other.slug}.html">${esc(other.title)}</a><p>${esc(other.description)}</p></li>`).join('')}</ul></aside>`;
 const articleBody=`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">${esc(title)}</a> / <a href="/guides/">Guides</a> / <span aria-current="page">${esc(a.title)}</span></nav><article><p class="guide-kicker">${esc(label)}</p><h1>${esc(a.title)}</h1><p class="guide-lede">${esc(a.description)}</p><p class="guide-byline">By the <a href="/about.html">${esc(title)} project</a> · Published <time datetime="${a.published}">${displayDate(a.published)}</time> · Software guide</p>${a.editorialNote?`<aside class="guide-note" aria-label="Editorial context"><p>${esc(a.editorialNote)}</p></aside>`:''}${toc}${content}${connection}${questions}${sourcesBlock}<aside class="guide-note"><p>Prepared with AI assistance and checked against the linked software implementation. This guide explains the product; it is not a clinical review. <a href="/about.html">About ${esc(title)}</a>.</p></aside>${related}<p><a href="/guides/">Browse all public guides →</a></p></article>`;
 write(path,page(a.title+' | '+title,a.description,path,articleBody,'Article',{headline:a.title,author:{'@type':'Organization',name:title+' project',url:base+'about.html'},datePublished:a.published,dateModified:a.modified||a.published,mainEntityOfPage:base+path,image:base+'social-card.png'}));
}
const connectionContext=esc(site.finchnodeContext).replace('FinchNode','<a href="https://finchnode.com/">FinchNode</a>');
const about=`<p class="guide-kicker">About ${esc(title)}</p><h1>${esc(subject)}</h1><p class="guide-lede">${esc(description)}</p><section><h2>What this site does</h2><p>${esc(site.workflow)}</p></section><section><h2>A focused product</h2><p>${esc(relation)}</p><p>${connectionContext}</p></section><section><h2>Current availability</h2><p>${status}</p></section><section><h2>Public information and private records</h2><p>Guide search runs in your browser and covers public explanatory pages only. It does not access a patient session, index health records or send search terms to an analytics service. Opening the homepage or an article never starts a record import.</p><p>Read the <a href="/privacy.html">privacy and data-handling notice</a> before connecting. Medical questions belong with your care team; this site documents software behavior.</p></section><section><h2>Source code and corrections</h2><p>Inspect the <a href="${repository}">public ${esc(title)} repository</a> for implementation, license, setup and tests. For privacy questions or factual corrections, contact <a href="mailto:software@council.health">software@council.health</a>. Please do not include private health records in a public GitHub issue.</p></section><p><a href="/${articlePath}">${esc(headline)} →</a></p>`;
write('about.html',page('About '+title+' | Product, guides & source code',`Learn what ${title} does, how its workflow works, and where to find source code, privacy details and project contact information.`,'about.html',about,'AboutPage'));
const records=[{url:'/',name:title+' — '+subject,text:description,terms:site.workflow},...articles.map(a=>({url:`/guides/${a.slug}.html`,name:a.title,text:a.description,terms:[...a.sections.flatMap(s=>[s.heading,...s.paragraphs,...(s.items||[])]),...(a.questions||[]).flatMap(q=>[q.question,q.answer]),a.finchnode?.text||''].join(' ')})),{url:'/about.html',name:'About '+title,text:'Product purpose, current availability, source code and contact information.',terms:relation},{url:'/privacy.html',name:'Privacy and data handling',text:'Authorization, retention, downloads, session access, revocation and privacy contact.',terms:'consent deletion records security sharing'}];
write('guides/index.html',page(title+' guides & site search',`Search public ${title} guides, product information and privacy explanations. Search stays in this browser and does not include private health records.`,'guides/',`<p class="guide-kicker">${esc(label)}</p><h1>${esc(title)} guides & site search</h1><p class="guide-lede">${esc(site.guideIntro)}</p><form role="search" id="guide-search" hidden><label for="guide-query">Search public ${esc(title)} pages</label><input id="guide-query" type="search" placeholder="Search topics, features or privacy" autocomplete="off" spellcheck="false" maxlength="200" aria-describedby="search-help"><p id="search-help">Search stays in this browser. Private health records are never included.</p></form><p id="search-count" role="status" aria-live="polite">${records.length} public pages</p><ul class="guide-results">${records.map(r=>`<li data-search="${esc(r.name+' '+r.text+' '+r.terms)}"><h2><a href="${r.url}">${esc(r.name)}</a></h2><p>${esc(r.text)}</p></li>`).join('')}</ul><p id="search-empty" hidden>No matching pages. Try a shorter phrase or clear your search to browse all guides.</p><script type="module" src="/guide-search.js"></script>`,'CollectionPage'));
write('guide-search.js',`const form=document.getElementById('guide-search');\nconst input=document.getElementById('guide-query');\nconst rows=[...document.querySelectorAll('[data-search]')];\nform.hidden=false;\nform.addEventListener('submit',event=>event.preventDefault());\ninput.addEventListener('input',()=>{const words=input.value.toLocaleLowerCase().trim().split(/\\s+/u).filter(Boolean);let count=0;for(const row of rows){const matches=words.every(word=>row.dataset.search.toLocaleLowerCase().includes(word));row.hidden=!matches;if(matches)count++;}document.getElementById('search-count').textContent=count+' public '+(count===1?'page':'pages');document.getElementById('search-empty').hidden=count>0;});`);
const oldPrivacy=readFileSync('public/privacy.html','utf8');
const privacy=oldPrivacy.match(/<main(?:\s[^>]*)?>([\s\S]*?)<\/main>/)?.[1];
if(!privacy)throw new Error('Privacy content missing');
write('privacy.html',page(title+' privacy & data handling',`Read how ${title} handles authorized records, temporary sessions, local copies, revocation and privacy requests.`,'privacy.html',privacy));
const routes=['','guides/',...articlePaths,'about.html','privacy.html'];
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(path=>`<url><loc>${esc(base+path)}</loc>${articlePaths.includes(path)?`<lastmod>${articles[articlePaths.indexOf(path)].modified||articles[articlePaths.indexOf(path)].published}</lastmod>`:''}</url>`).join('')}</urlset>`);
write('robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${base}sitemap.xml`);
write('404.html',page('Page not found | '+title,'This page could not be found. Browse public guides or return to the homepage.','404.html','<h1>Page not found</h1><p><a href="/">Return home</a> or <a href="/guides/">search the public guides</a>.</p>').replace('index,follow,max-image-preview:large','noindex,follow'));
write('favicon.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="${color}"/><text x="32" y="45" text-anchor="middle" font-family="Arial,sans-serif" font-weight="700" font-size="42" fill="white">${title[0]}</text></svg>`);
writeFileSync('index.html',`<!doctype html><html lang="en"><head>${head(title+' | '+subject,description)}<link rel="stylesheet" href="/editorial.css"></head><body><div id="root"></div><noscript><p>Public guides work without JavaScript. Enable JavaScript to use the private import workspace.</p></noscript><script type="module" src="/app/main.tsx"></script></body></html>\n`);
// Colors are generated from reviewed, fixed theme values, never user input.
write('editorial.css',readFileSync('scripts/editorial.css','utf8').replaceAll('THEME_COLOR',color).replaceAll('THEME_PAPER',paper));
console.log(`${title}: generated ${routes.length} public pages and sitemap`);
